/**
 * Phase 315 — Assessment Matrix Discovery Test (spec utama)
 *
 * SMOKE RUN PROTOCOL (D-07 — WAJIB dijalankan dulu sebelum full run):
 *   cd tests && npx playwright test assessment-matrix --grep "Scenario 5"
 *
 * FULL RUN:
 *   cd tests && npx playwright test assessment-matrix
 *
 * PRE-RUN CHECKLIST:
 *   1. Kestrel STOPPED (Ctrl+C di terminal `dotnet run`) sebelum TEARDOWN — Pitfall 2
 *      mitigation. Selama exam-taking phase Kestrel WAJIB running (page.goto butuh app);
 *      tetapi sebelum globalTeardown RESTORE (SET SINGLE_USER WITH ROLLBACK IMMEDIATE)
 *      Kestrel SEBAIKNYA stopped supaya tidak ada koneksi in-flight saat RESTORE.
 *      Praktis: jalankan `dotnet run` di terminal A, run Playwright di terminal B; Ctrl+C
 *      terminal A SETELAH Playwright print "Running 1 test using 1 worker" tapi SEBELUM
 *      teardown trigger (atau biarkan otomatis — teardown catch + log manual restore cmd).
 *   2. SQL Server Express `localhost\SQLEXPRESS` reachable (`sqlcmd -S localhost\SQLEXPRESS -E -Q "SELECT 1"`)
 *   3. Database `HcPortalDB_Dev` exists + table AssessmentSessions Id range 9001-9018 EMPTY
 *   4. Fixture users seeded (DB lokal): rino.prasetyo@pertamina.com (coachee),
 *      iwan3@pertamina.com (coachee2), meylisa.tjiang@pertamina.com (hc)
 *
 * Architecture (per CONTEXT.md D-01..D-07 + RESEARCH.md):
 *   - State file `tests/.matrix-state.json` ditulis oleh tests/e2e/global.setup.ts
 *     (Plan 03) — berisi 10 ScenarioConfig (7 discovery S1-S7 + 3 sentinel S8-S10).
 *   - Spec ini membaca state file di module scope lalu dynamic-resolve config per test.
 *   - Per scenario discovery (S1-S7): 3 BrowserContext isolated (peserta1, peserta2, HC).
 *     peserta1 = coachee (rino.prasetyo) — normal answer.
 *     peserta2 = coachee2 (iwan3) — sabotage answer pertama (deterministic via
 *     examMatrix.takeExam options.sabotageOneAnswer=true; CONTEXT.md Claude's Discretion).
 *     HC = meylisa.tjiang — grade essay jika `cfg.hasEssay`.
 *   - Sentinel S8 [META-AllCorrect]: peserta1 all-correct → expect 100% score.
 *   - Sentinel S9 [META-AllWrong]: peserta1 all-wrong (clone cfg dengan correctOptionIds=[]
 *     dan kirim ke takeExam) → expect 0% score.
 *   - Sentinel S10 [META-CollectorCheck]: `test.fail()` annotation (D-06). Body sengaja
 *     force critical softAssert fail → collector record meta finding → SkipScenarioError
 *     thrown → Playwright treat sebagai expected failure → exit 0. Kalau body sukses tanpa
 *     throw (collector rusak silently) → Playwright treat sebagai unexpected pass → exit non-0.
 *   - Continue-on-fail: SkipScenarioError dicatch per test body. Critical fail di 1 scenario
 *     TIDAK halt sisa scenario (matrix discovery focus).
 *   - Pattern H race-tolerant outcome: verifyResultPage + sentinel result navigation pakai
 *     race-tolerant locator (`.score-badge, [data-score], .result-score`) — minimal salah
 *     satu indicator visible. Lihat helpers/examMatrix.ts:258-274.
 *
 * Source-of-truth design spec: docs/superpowers/specs/2026-05-11-assessment-matrix-test-design.md
 * (commit 94bacecf).
 *
 * Output:
 *   - docs/test-reports/YYYY-MM-DD-assessment-matrix.md (generated by globalTeardown
 *     via matrixReport.collector.flush — preserve findings sebelum RESTORE).
 *   - test-results/matrix-s{N}-{step-slug}.png (screenshots per finding, ditulis softAssert).
 */

import { test, type Browser } from '@playwright/test';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import type { ScenarioConfig } from './helpers/matrixTypes';
import { takeExam, gradeEssaysAsHc, verifyResultPage } from './helpers/examMatrix';
import { softAssert, SkipScenarioError } from './helpers/matrixReport';

// Serial mode — singleton `collector` di matrixReport.ts + sequential scenario execution
// (RESEARCH.md § Pattern 3 line 573). fullyParallel=false sudah di playwright.config.ts:7
// tapi konfirmasi di sini agar describe behavior eksplisit.
test.describe.configure({ mode: 'serial' });

// Per-test timeout extension (Rule 3 — default 60s di playwright.config.ts:6 tidak cukup
// untuk 3 BrowserContext × 3-soal exam × HC grading × verify result page). Smoke run S5
// confirm 60s timeout = test fail di question 2/3 saat submit-exam step.
// 240s memberikan margin untuk discovery scenarios; sentinel S8-S10 lebih ringan tapi pakai
// nilai sama untuk konsistensi.
const SCENARIO_TIMEOUT_MS = 240_000;

// Read state file ditulis global.setup.ts.
//
// Path resolver: __dirname adalah `tests/e2e/`, parent (`..`) adalah `tests/`. Pakai
// absolute resolve supaya independent dari cwd Playwright runner (cwd bisa `tests/` saat
// run via `cd tests && npx playwright test`, atau worktree-root via custom invocation).
// Konsisten dengan global.setup.ts + global.teardown.ts yang juga di-fix Rule 3 — tulis
// ke `tests/.matrix-state.json` absolute path.
//
// Graceful fallback: kalau state file missing (mis. saat `--list` discovery sebelum
// globalSetup pernah jalan), pakai placeholder state supaya Playwright tetap bisa parse
// 10 test blocks + listing. Test body akan throw saat `getScenario()` kalau placeholder
// — clear error message ke user (T-315-SPEC-01 threat: accept disposition).
const STATE_FILE = resolve(__dirname, '..', '.matrix-state.json');
type MatrixState = { snapshotPath: string; seededAt: string; scenarios: ScenarioConfig[] };
let state: MatrixState;
try {
  const stateRaw = readFileSync(STATE_FILE, 'utf-8');
  state = JSON.parse(stateRaw);
} catch (e) {
  // File missing → placeholder. Test execution akan fail via getScenario() throw.
  // Listing tetap work (10 test definitions ter-register).
  console.warn(
    `[assessment-matrix] State file ${STATE_FILE} missing — pakai placeholder. ` +
      `Test execution akan fail di getScenario() kalau ngga ada globalSetup run. ` +
      `Detail: ${(e as Error)?.message ?? e}`
  );
  state = { snapshotPath: '', seededAt: '', scenarios: [] };
}

/**
 * Resolve ScenarioConfig by id, throw kalau missing (state corrupted).
 * Dipakai per-test untuk dapat config tanpa pollution state ke top-level.
 */
function getScenario(id: number): ScenarioConfig {
  const cfg = state.scenarios.find((s) => s.id === id);
  if (!cfg) {
    throw new Error(
      `Scenario id=${id} tidak ditemukan di tests/.matrix-state.json. ` +
        `State file kemungkinan corrupted — re-run globalSetup.`
    );
  }
  return cfg;
}

/**
 * Orchestrate 1 discovery scenario (S1-S7) — 3 BrowserContext isolated.
 *   peserta1 = coachee (rino.prasetyo) takeExam normal.
 *   peserta2 = coachee2 (iwan3) takeExam dengan sabotageOneAnswer=true.
 *   HC = meylisa.tjiang gradeEssaysAsHc jika cfg.hasEssay.
 *   Final: verifyResultPage untuk kedua peserta.
 *
 * SkipScenarioError catch supaya continue-on-fail behavior; finding sudah ter-record
 * via softAssert wrapper di dalam helpers (examMatrix.ts). Cleanup context wajib di
 * finally — prevent resource leak across sequential scenarios.
 */
async function runDiscoveryScenario(browser: Browser, cfg: ScenarioConfig): Promise<void> {
  const ctx1 = await browser.newContext();
  const page1 = await ctx1.newPage();
  const ctx2 = await browser.newContext();
  const page2 = await ctx2.newPage();
  const ctxHc = await browser.newContext();
  const pageHc = await ctxHc.newPage();

  try {
    // Peserta 1 — jawab benar semua. Login + StartExam + SignalR ready + per-question
    // save + Submit handled by helper (positive saveIndicator confirmation per A2 verdict).
    await takeExam(page1, cfg, 'coachee', cfg.sessionIdPeserta1);

    // Peserta 2 — sabotage question index 0 (deterministic, CONTEXT.md "Claude's Discretion"
    // line 71): MC=first wrong option, MA=skip first correct option, Essay=empty string.
    await takeExam(page2, cfg, 'coachee2', cfg.sessionIdPeserta2, { sabotageOneAnswer: true });

    // HC grading — hanya kalau scenario punya essay question.
    if (cfg.hasEssay) {
      await gradeEssaysAsHc(pageHc, cfg);
    }

    // Verify result page (race-tolerant — Pattern H accept salah satu indicator
    // `.score-badge, [data-score], .result-score`).
    await verifyResultPage(page1, cfg, 'coachee');
    await verifyResultPage(page2, cfg, 'coachee2');
  } catch (e) {
    if (e instanceof SkipScenarioError) {
      // Critical fail sudah ter-record di collector via softAssert; lanjut scenario berikut.
      console.log(`[S${cfg.id}] Critical fail — skip sisa step scenario: ${e.message}`);
      return;
    }
    // Unexpected error — let Playwright handle (will fail test, recorded di run statistics).
    throw e;
  } finally {
    // Defensive close — context may already be closed mid-scenario (page-closed cascade,
    // navigate race, atau crash). throw dari ctx.close() ESCAPE finally → Playwright treat
    // test sebagai timeout-failed + halt sequential queue (`9 did not run`). Phase 316 fix
    // (Plan 02 deviation Rule 3): swallow close error supaya catch SkipScenarioError
    // semantic preserved + serial queue continue ke S2-S10.
    await ctx1.close().catch(() => { /* already closed — non-fatal */ });
    await ctx2.close().catch(() => { /* already closed — non-fatal */ });
    await ctxHc.close().catch(() => { /* already closed — non-fatal */ });
  }
}

// =====================================================================
// Group 1: Matrix Discovery — mixed soal-type per assessment-type (S1-S4)
// Tujuan: sweep 4 tipe assessment (Manual/Online/PreTest/PostTest) dengan
// kombinasi soal MC+MA+Essay. Soal mix di setiap scenario sama (3 soal: 1 MC + 1 MA + 1 Essay).
// =====================================================================

test('Scenario 1: S1 Manual Mixed (MC + MA + Essay)', async ({ browser }) => {
  test.setTimeout(SCENARIO_TIMEOUT_MS);
  await runDiscoveryScenario(browser, getScenario(1));
});

test('Scenario 2: S2 Online Mixed (MC + MA + Essay)', async ({ browser }) => {
  test.setTimeout(SCENARIO_TIMEOUT_MS);
  await runDiscoveryScenario(browser, getScenario(2));
});

test('Scenario 3: S3 PreTest Mixed (MC + MA + Essay)', async ({ browser }) => {
  test.setTimeout(SCENARIO_TIMEOUT_MS);
  await runDiscoveryScenario(browser, getScenario(3));
});

test('Scenario 4: S4 PostTest Mixed (MC + MA + Essay)', async ({ browser }) => {
  test.setTimeout(SCENARIO_TIMEOUT_MS);
  await runDiscoveryScenario(browser, getScenario(4));
});

// =====================================================================
// Group 2: Matrix Discovery — single-type Online (S5-S7)
// Tujuan: isolate per tipe soal di assessment-type yang sama (Online), supaya
// finding bisa di-attribute ke tipe soal specific tanpa cross-interference.
// =====================================================================

test('Scenario 5: S5 Online MC only (3 MultipleChoice questions)', async ({ browser }) => {
  test.setTimeout(SCENARIO_TIMEOUT_MS);
  await runDiscoveryScenario(browser, getScenario(5));
});

test('Scenario 6: S6 Online MA only (3 MultipleAnswer questions)', async ({ browser }) => {
  test.setTimeout(SCENARIO_TIMEOUT_MS);
  await runDiscoveryScenario(browser, getScenario(6));
});

test('Scenario 7: S7 Online Essay only (3 Essay questions)', async ({ browser }) => {
  test.setTimeout(SCENARIO_TIMEOUT_MS);
  await runDiscoveryScenario(browser, getScenario(7));
});

// =====================================================================
// Group 3: Meta-validation sentinels (S8-S10) — Layer 3 self-check
// Tujuan: verifikasi test infrastructure (helpers + collector + report) bekerja
// dengan benar. Finding dari sentinel TIDAK ikut summary statistik discovery
// (matrixReport.renderReport pisah ke `## Meta-validation results` via isMeta flag).
// =====================================================================

test('Scenario 8: META-AllCorrect Sentinel (expect 100% score)', async ({ browser }) => {
  test.setTimeout(SCENARIO_TIMEOUT_MS);
  // [META-AllCorrect]: peserta1 jawab semua benar (no sabotage), HC grading penuh.
  // Expect: result page show score 100% (atau pattern /100|sempurna|full/i). Kalau
  // tidak 100% → meta finding (collector record dengan isMeta=true).
  const cfg = getScenario(8);

  const ctx1 = await browser.newContext();
  const page1 = await ctx1.newPage();
  const ctxHc = await browser.newContext();
  const pageHc = await ctxHc.newPage();

  try {
    // Peserta 1 — semua benar (no sabotage)
    await takeExam(page1, cfg, 'coachee', cfg.sessionIdPeserta1);

    // HC grade essay full marks via helper (scoreValue diisi dari cfg.questions[i].scoreValue)
    if (cfg.hasEssay) {
      await gradeEssaysAsHc(pageHc, cfg);
    }

    // Sentinel meta-assert: race-tolerant locator + regex match expected 100% pattern.
    // isMeta=true → collector pisahkan ke section `## Meta-validation results`.
    await softAssert(
      {
        scenario: cfg,
        step: 'sentinel-all-correct-score',
        severity: 'minor',
        page: page1,
        isMeta: true,
      },
      async () => {
        await page1.goto(`/CMP/Results/${cfg.sessionIdPeserta1}`);
        const scoreLocator = page1.locator('.score-badge, [data-score], .result-score').first();
        await scoreLocator.waitFor({ state: 'visible', timeout: 10_000 });
        const scoreText = (await scoreLocator.textContent()) ?? '';
        if (!/100|full|sempurna/i.test(scoreText)) {
          throw new Error(`Sentinel AllCorrect expected score 100%/sempurna, got: "${scoreText.trim()}"`);
        }
      },
      'Sentinel AllCorrect: peserta1 jawab semua benar → score 100%/sempurna'
    );
  } catch (e) {
    if (e instanceof SkipScenarioError) {
      console.log(`[S${cfg.id} META-AllCorrect] Critical fail — collector record: ${e.message}`);
      return;
    }
    throw e;
  } finally {
    await ctx1.close();
    await ctxHc.close();
  }
});

test('Scenario 9: META-AllWrong Sentinel (expect 0% score)', async ({ browser }) => {
  test.setTimeout(SCENARIO_TIMEOUT_MS);
  // [META-AllWrong]: peserta1 sengaja jawab semua salah → expect score 0%.
  // Strategi: clone cfg dengan correctOptionIds=[] supaya findWrongOption di examMatrix.ts
  // selalu pick option yang tidak ada di correctOptionIds (= seluruh option). Untuk MA,
  // correctOptionIds.slice(1) = [] (no checkbox ticked → no save → 0 score). Untuk Essay,
  // jawaban kosong (HC grade 0).
  //
  // PENTING: sabotageOneAnswer=true hanya sabotage question index 0. Untuk full-wrong kita
  // pakai pendekatan clone cfg (mutate questions[].correctOptionIds = []) + jangan pass
  // sabotageOneAnswer. Dengan correctOptionIds=[], helper takeExam akan:
  //   - MC: pick correctOptionIds[0] = undefined → throw di page.check. Solusi: pass
  //     sabotageOneAnswer=true AND clone, supaya helper masuk branch findWrongOption yang
  //     iterate allOptionIds. Tapi sabotage hanya index 0.
  // Pendekatan pragmatic: clone cfg dengan correctOptionIds=[<first wrong>] supaya helper
  // jawab opsi salah untuk MC, AND untuk MA correctOptionIds.slice(1)=[] (no tick).
  const cfg = getScenario(9);
  const cfgAllWrong: ScenarioConfig = {
    ...cfg,
    questions: cfg.questions.map((q) => {
      if (q.type === 'MultipleChoice' || q.type === 'MultipleAnswer') {
        // Pilih option salah pertama sebagai "correct" supaya helper jawab dengan opsi yang
        // sebenarnya salah (DB grading later akan score 0). Untuk MA, slice(1)=[] tetap
        // sabotage karena helper tick `correctOptionIds` array.
        const wrong = q.allOptionIds.filter((id) => !q.correctOptionIds.includes(id));
        return { ...q, correctOptionIds: wrong.length > 0 ? [wrong[0]] : [] };
      }
      // Essay: correctOptionIds kosong dari awal; helper kirim string kosong saat
      // sabotageOneAnswer (atau jawaban benar tanpa sabotage). Untuk AllWrong consistency
      // pakai sabotageOneAnswer di call site supaya Essay kosong → HC grade 0.
      return q;
    }),
  };

  const ctx1 = await browser.newContext();
  const page1 = await ctx1.newPage();
  const ctxHc = await browser.newContext();
  const pageHc = await ctxHc.newPage();

  try {
    // sabotageOneAnswer=true → Essay index 0 kirim "" (HC grade 0). MC/MA pakai cfgAllWrong
    // questions yang sudah swap correctOptionIds ke wrong option.
    await takeExam(page1, cfgAllWrong, 'coachee', cfg.sessionIdPeserta1, { sabotageOneAnswer: true });

    if (cfg.hasEssay) {
      // HC grade essay dengan scoreValue=0 untuk simulate all-wrong (helper pakai
      // q.scoreValue dari cfg, jadi kita override via cfgAllWrong essay scoreValue=0).
      const cfgZeroEssay: ScenarioConfig = {
        ...cfg,
        questions: cfg.questions.map((q) => (q.type === 'Essay' ? { ...q, scoreValue: 0 } : q)),
      };
      await gradeEssaysAsHc(pageHc, cfgZeroEssay);
    }

    await softAssert(
      {
        scenario: cfg,
        step: 'sentinel-all-wrong-score',
        severity: 'minor',
        page: page1,
        isMeta: true,
      },
      async () => {
        await page1.goto(`/CMP/Results/${cfg.sessionIdPeserta1}`);
        const scoreLocator = page1.locator('.score-badge, [data-score], .result-score').first();
        await scoreLocator.waitFor({ state: 'visible', timeout: 10_000 });
        const scoreText = (await scoreLocator.textContent()) ?? '';
        if (!/\b0\b|nol|zero/i.test(scoreText)) {
          throw new Error(`Sentinel AllWrong expected score 0/nol, got: "${scoreText.trim()}"`);
        }
      },
      'Sentinel AllWrong: peserta1 jawab semua salah → score 0%/nol'
    );
  } catch (e) {
    if (e instanceof SkipScenarioError) {
      console.log(`[S${cfg.id} META-AllWrong] Critical fail — collector record: ${e.message}`);
      return;
    }
    throw e;
  } finally {
    await ctx1.close();
    await ctxHc.close();
  }
});

// S10 SENGAJA gagal — `test.fail()` annotation (D-06). Body force critical softAssert
// fail → collector record meta finding + throw SkipScenarioError. Playwright treat sebagai
// expected failure → exit 0. Kalau body pass tanpa throw (collector swallow silently),
// Playwright treat sebagai unexpected pass → exit non-0 (collector rusak terdeteksi).
//
// CATATAN: annotation `test.fail()` di-call di dalam test body (sintaks Playwright valid;
// equivalent dengan `test.fail('name', async ...)` outer form). Kita pakai inner form
// supaya literal `test(` tetap di start-of-line untuk konsistensi 10 test blocks.
test('Scenario 10: META-CollectorCheck Sentinel (sengaja gagal — verifikasi collector working)', async ({ browser }) => {
  test.fail(); // expected-failure annotation — exit 0 saat body throw, exit non-0 kalau pass tanpa throw.
  test.setTimeout(SCENARIO_TIMEOUT_MS);

  const cfg = getScenario(10);

  const ctx1 = await browser.newContext();
  const page1 = await ctx1.newPage();

  try {
    // Force critical softAssert fail. severity='critical' → throw SkipScenarioError.
    // isMeta=true → finding masuk section `## Meta-validation results` di report.
    await softAssert(
      {
        scenario: cfg,
        step: 'sentinel-collector-check',
        severity: 'critical',
        page: page1,
        isMeta: true,
      },
      async () => {
        // Buka result page dulu supaya screenshot ada konten (bukan blank). Tidak wajib
        // success — boleh fail navigation juga, intent-nya adalah trigger softAssert fail.
        await page1.goto(`/CMP/Results/${cfg.sessionIdPeserta1}`).catch(() => {});
        throw new Error(
          'Sentinel CollectorCheck intentionally fails — verifikasi collector record finding ' +
            'sebagai meta + throw SkipScenarioError untuk test.fail() expected-failure semantics.'
        );
      },
      'Sentinel CollectorCheck: collector record meta finding + throw SkipScenarioError'
    );
  } finally {
    await ctx1.close();
  }
});
